# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IbmTruth',
            fields=[
                ('co_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('web_site', models.CharField(blank=True, max_length=250, null=True)),
                ('hq_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('co_email', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sic_code', models.CharField(blank=True, max_length=500, null=True)),
                ('sales', models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True)),
                ('it_budget', models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True)),
                ('sales_growth', models.CharField(blank=True, max_length=250, null=True)),
                ('fiscal_year_end', models.CharField(blank=True, max_length=25, null=True)),
                ('no_employees', models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True)),
                ('fortune_rank', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('hq_street', models.CharField(blank=True, max_length=500, null=True)),
                ('hq_city', models.CharField(blank=True, max_length=250, null=True)),
                ('hq_state', models.CharField(blank=True, max_length=25, null=True)),
                ('hq_zip', models.CharField(blank=True, max_length=12, null=True)),
                ('pub_priv', models.CharField(blank=True, max_length=25, null=True)),
                ('dnus_no', models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True)),
                ('duns_parent', models.CharField(blank=True, max_length=25, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'ibm_truth',
                'managed': False,
            },
        ),
    ]
