# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewone', '0002_authortabletest_pubmedtitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubmedAuthor',
            fields=[
                ('author_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('complete_addr', models.TextField(blank=True, null=True)),
                ('pmid', models.DecimalField(decimal_places=0, max_digits=25)),
                ('department', models.TextField(blank=True, null=True)),
                ('institution', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('tools_used', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'authortable1_pubmed',
                'managed': False,
            },
        ),
    ]
